---
version: '2'

services:

    app:
        build:
            context: ./build/php
            args:
                remote_host : 192.168.1.100
        container_name: app
        command: php -S app:80 -t public/ public/app.php
        working_dir: /code
        volumes:
            - "$PWD:/code"
            - "../common:/lib/common"
        ports:
            - "8080:80"
        environment:
            - APP_ENV=dev
            - PHP_IDE_CONFIG="serverName=app"
    tests:
        build:
            context: ./build/php
            args:
                remote_host : 192.168.1.100
        container_name: tests
        working_dir: /code
        command: sleep 100d
        volumes:
            - "$PWD:/code"
        environment:
            - PHP_IDE_CONFIG="serverName=app"
        depends_on:
            - redis

    composer:
        build:
            context: ./build/php
        container_name: composer
        working_dir: /code
        entrypoint:
          - composer
        volumes_from:
            - app

    redis:
        container_name: redis
        image: redis:3.2.4-alpine
        command: redis-server --appendonly yes
        restart: unless-stopped
        ports:
          - "50002:6379"

    redis-gui:
        image: tenstartups/redis-commander
        container_name: redis-gui
        command:  --redis-host redis
        restart: unless-stopped
        ports:
          - "50000:8081"
        depends_on:
          - redis